In [1]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.datasets import load_boston
from sklearn.model_selection import cross_val_score, KFold
from sklearn.linear_model import LassoCV, RidgeCV, Lasso, Ridge

In [3]:
boston = load_boston()
X, y = boston['data'], boston['target']

In [13]:
boston.feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [17]:
lasso = Lasso(alpha=1)
lasso.fit(X, y)
lasso.coef_

array([-0.06343729,  0.04916467, -0.        ,  0.        , -0.        ,
        0.9498107 ,  0.02090951, -0.66879   ,  0.26420643, -0.01521159,
       -0.72296636,  0.00824703, -0.76111454])

In [18]:
lasso_cv = LassoCV(cv=3, random_state=17)
lasso_cv.fit(X, y)

LassoCV(cv=3, random_state=17)

In [19]:
lasso_cv.coef_

array([-0.07426626,  0.04945448, -0.        ,  0.        , -0.        ,
        1.804385  ,  0.01133345, -0.81324404,  0.27228399, -0.01542465,
       -0.74287183,  0.00892587, -0.70365352])

In [20]:
lasso_cv.alpha_

0.7248204283772595

In [22]:
cross_val_score(Lasso(lasso_cv.alpha_), X, y, cv=3, scoring='neg_mean_squared_error')

array([-19.52864329, -55.05546281, -66.85588649])

In [26]:
abs(cross_val_score(Lasso(lasso_cv.alpha_), X, y, cv=3, scoring='neg_mean_squared_error')).mean()

47.14666419712137