In [58]:
import numpy as np

In [59]:
A = [[2, 3], [4, 6]]

In [60]:
np.linalg.det(A)

0.0

In [61]:
A = A + np.diag([2,2])

In [62]:
A

array([[4, 3],
       [4, 8]])

In [63]:
np.linalg.det(A)

19.999999999999996

In [47]:
np.linalg.eig(A)[0]

array([-4.99999997e-08,  8.00000005e+00])

In [48]:
A_hat = np.linalg.inv(A)

In [49]:
A_hat

array([[-15000000.02454868,   7500000.26227434],
       [ 10000000.01636579,  -5000000.00818289]])

In [29]:
np.linalg.eig(A_hat)[0]

array([1.99874922e+02, 1.25078223e-01])