In [32]:
import numpy as np


In [59]:
A = [[2, 3], [4, 6]]

In [60]:
np.linalg.det(A)

0.0

In [61]:
A = A + np.diag([2,2])

In [62]:
A

array([[4, 3],
       [4, 8]])

In [63]:
np.linalg.det(A)

19.999999999999996

In [47]:
np.linalg.eig(A)[0]

array([-4.99999997e-08,  8.00000005e+00])

In [48]:
A_hat = np.linalg.inv(A)

In [49]:
A_hat

array([[-15000000.02454868,   7500000.26227434],
       [ 10000000.01636579,  -5000000.00818289]])

In [29]:
np.linalg.eig(A_hat)[0]

array([1.99874922e+02, 1.25078223e-01])

In [1]:
from math import comb

In [6]:
comb(5, 4)

5

In [27]:
def get_p(p, N):
    ans = 0
    m = int(N/2) + 1
    for i in range(m, N+1):
        ans += comb(N, i) * p**i * (1-p)**(N-i)
    return ans

In [30]:
get_p(0.5, 5)

0.5187450006

In [22]:
int(5.9)

5

In [45]:
A = np.array([[1,2, 3], [1, 2, 4]])

In [46]:
A

array([[1, 2, 3],
       [1, 2, 4]])

In [50]:
B = np.diag((2, 3, 1))

In [51]:
B

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 1]])

In [52]:
A @ B

array([[2, 6, 3],
       [2, 6, 4]])