In [2]:
import numpy as np


In [45]:
X = np.random.normal(loc=1, scale=10, size=(3, 2))
X

array([[10.60450908, 20.72445345],
       [ 0.62534229, -9.36561916],
       [-1.76870539, 11.83132247]])

In [51]:
m = np.mean(X, axis=0)
print(m)
std = np.std(X, axis=0)
X_norm = ((X - m)  / std)
print(np.mean([m[0],m[1]]))
print(np.mean(X))


[3.15371533 7.73005226]
5.441883791516787
5.441883791516787


In [47]:
X_norm

array([[ 1.39048957,  1.02951253],
       [-0.47185259, -1.35444547],
       [-0.91863698,  0.32493295]])

In [52]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [56]:
r = np.sum(Z, axis=1)
print(np.nonzero(r > 10))

(array([1, 4, 5]),)


In [59]:
A = np.eye(3)
B = np.eye(3)
print(A)
print()
print(B)
print()
AB = np.vstack((A, B))
print(AB)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
